## count the reads for each sample in given CSV files generated by demux
## example:  sh ~/count_read.sh  /data3/Downloads/Klein/*18104Bkl/00*/*csv >18104Bkl.read_count.txt

cat $* | perl -ne 'next if /^Flowcell/i; next unless /\S/; @t=split /,/, $_; $h{$t[3]} += $t[6]; END{map{print $_, "\t", $h{$_}, "\n"}keys %h;}' |sort -k2,2n

